// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uitkydedbfjelpafzrdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpdGt5ZGVkYmZqZWxwYWZ6cmRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzOTg2MTUsImV4cCI6MjA1ODk3NDYxNX0.Q0IpjPj_itNecId5jvRZ4JGVY6wrhRaY6WPAYRl-EBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);